[workspace]
changelog_config = "cliff.toml"
changelog_update = true

release_commits = "^feat[(:]"

features_always_increment_minor = true

dependencies_update = true

git_tag_enable = true
git_release_enable = true
git_release_type = "auto"

pr_labels = ["release"]

allow_dirty = false
publish_allow_dirty = false
semver_check = false

[changelog]
protect_breaking_commits = true
